"use strict";
// Inject bundled PalBuilder context into a pal workspace WITHOUT clobbering user content.
//   - .claude/skills/<name>/SKILL.md  (copied from bundle; palsync-owned, progressive-disclosure depth)
//   - CLAUDE.palsync.md  = the SINGLE palsync-owned doc: the static coding contract (bundled CLAUDE.md)
//                          + the templated sync/creation/dataset rules, under one version stamp.
//                          Regenerated wholesale each setup, so the rules live in ONE file and can't
//                          drift between two.
//   - CLAUDE.md          = the user's file, with a tiny managed block that `@CLAUDE.palsync.md`-imports
//                          the owned doc. The import is on its own line and un-backticked — Claude
//                          Code's import parser skips code spans, so a backticked @ref would NOT load.
// Re-running setup rewrites the owned doc + the managed block + prunes retired skills; a teammate's own
// CLAUDE.md notes (outside the markers) survive. `contextStatus()` compares the doc's stamp to the
// installed build so `palsync status` can flag a workspace that needs a relaunch to refresh.
const fs = require("fs/promises");
const path = require("path");

const BUNDLE_DIR = path.join(__dirname, "..", "..", "bundled-context");
const VERSION = require("../../package.json").version;

// Stamp the owned doc with the palsync version that generated it, so `palsync status` can flag a
// workspace whose context predates the installed build (relaunch re-injects and refreshes it).
const STAMP_RE = /<!--\s*palsync-context\s+v([0-9][^\s]*)/;
function stampComment() {
    return "<!-- palsync-context v" + VERSION + " — regenerated by palsync setup; do not edit by hand -->";
}

// Skill dir names palsync has shipped but later renamed/removed. Pruned from a workspace if present
// so a re-inject drops them (e.g. design-core → design-system-init + design-build). User-added skills
// (names palsync never owned) are never touched.
const RETIRED_SKILLS = ["design-core", "palbuilder-design", "design"];

// Every skill in the bundle loads every session — the bundle dir IS the inventory, discovered at
// inject time (see bundledSkills), so a newly-added skill ships automatically with no hand-kept
// list to drift out of sync. Skills cost no context until the agent opens one (only their
// name+description are read at startup); each skill's references/* ride along so a SKILL.md that
// links them always has them in the workspace.
const BEGIN = "<!-- >>> palsync managed block — do not edit; regenerated by palsync setup >>> -->";
const END = "<!-- <<< palsync managed block <<< -->";

// The sync-etiquette section that teaches the agent the palsync workflow (decision: conversational).
// cli=true renders the Pi flavor: palsync CLI subcommands instead of MCP tools, and lock-per-command
// instead of an always-on session lock (Pi has no MCP — it drives palsync through its shell CLI).
function syncSection(palName, { cli = false } = {}) {
    const T = cli
        ? { pull: "`palsync pull`", push: "`palsync push`", validate: "`palsync validate`",
            test: "`palsync test`", preview: "`palsync preview`", seo: "`palsync seo-audit`",
            merge: "`palsync merge`", status: "`palsync status`", datasets: "`palsync sync-datasets`",
            screenshot: "`palsync screenshot`", fetch: "`palsync fetch`", specLint: "`palsync spec-lint`",
            regression: "`palsync regression`", skip: "the `--skip-validation` flag" }
        : { pull: "`pal_pull`", push: "`pal_push`", validate: "`pal_validate`",
            test: "`pal_test`", preview: "`pal_preview`", seo: "`pal_seo_audit`",
            merge: "`pal_merge`", status: "`pal_status`", datasets: "`pal_sync_datasets`",
            screenshot: "`pal_screenshot`", fetch: "`pal_fetch`", specLint: "`pal_spec_lint`",
            regression: "`pal_regression`" };
    const conn = cli
        ? "This pal" + (palName ? " (**" + palName + "**)" : "") + " is connected to CloudPiston via the **palsync CLI** — run its subcommands in your shell (e.g. `palsync push`, `palsync pull`). palsync takes the pal lock for each push/pull and releases it; there is no always-on session lock."
        : "This pal" + (palName ? " (**" + palName + "**)" : "") + " is connected to CloudPiston via the **palsync** MCP server and is **locked for your session**.";
    return [
        "## palsync — sync etiquette (managed)",
        "",
        conn,
        "",
        "**BEFORE writing any pal code, read the skill files** in `.claude/skills/` (`palbuilder-core`",
        "for platform foundations + ES3 rules + `pal.json`, `palbuilder-data` for datasets/payloads/HTTP,",
        "`palbuilder-frontend` for pages/fragments/c: tags, `palbuilder-backend` for workflow .js,",
        "`palbuilder-jobs-http` for background jobs / long-running work). PalBuilder is a proprietary",
        "dialect you do NOT know from training — your defaults (object literals, `let`/`const`, normal",
        "HTML habits) produce code that saves but then FAILS to compile or render. The skills are the",
        "rules; follow them literally.",
        "",
        "The working loop:",
        "",
        "1. " + T.pull + " before starting significant work. Pull is a safe sync: it preserves NEW",
        "   un-pushed files (and carries their `pal.json` entries forward), and it REFUSES — naming",
        "   the files — if it would overwrite un-pushed local edits.",
        "2. Write code following the skills. Then run **" + T.validate + "** — an instant offline check",
        "   that catches the known PalBuilder breakers (object literals in workflows, `let`/`const`,",
        "   unclosed void tags, undocumented `c:` attributes, `${}` in inline scripts). Fix every",
        "   ERROR it reports; each finding tells you exactly how.",
        "3. **Offer to " + T.push + "** when a meaningful change is done (palsync does not auto-push).",
        "   Push runs " + T.validate + " automatically and refuses on errors YOUR change introduced — fix",
        "   every one; each finding says exactly how. There is no bypass" + (cli ? " you should use (" + T.skip + " exists for humans only)" : "") + ". (Pre-existing errors",
        "   in a file you edit don't block you; only new ones do.)",
        "4. After pushing workflow or UI changes, **offer to " + T.test + "** — it runs the SERVER's own",
        "   validation and opens a live preview in the user's browser.",
        "5. **" + T.validate + " and " + T.test + " only prove the code COMPILES — not that it RENDERS.** A",
        "   workflow that validates can still THROW at runtime (bad SQL, a null, a column the table lacks)",
        "   and paint an error block instead of the UI. You MUST call **" + T.screenshot + "** after every push",
        "   that touches a page/fragment/workflow, and see a clean capture, before declaring that change",
        "   done — not optional, not \"if you have time.\" " + T.preview + " (CONSOLE/transaction) just opens",
        "   the render in the USER's browser; it does not show YOU anything. " + T.screenshot + " is different:",
        "   it drives an authenticated console screen too (replays the auth redirect chain in a headless",
        "   browser) and returns a PNG + a `renderError` if the workflow threw. For a WEB pal, " + T.fetch + "/",
        "   " + T.preview + " with `expect:[strings]` also count as verification. Only fall back to asking the",
        "   user to eyeball the screen themselves if the check tool reports itself unavailable (no Chromium,",
        "   or the auth replay failed) — never as a substitute for calling it. Preview/screenshot/fetch show",
        "   the LAST PUSHED version, so push before checking your latest edits.",
        "   - **Never report page content, saved data, or a completed click/type/submit flow as fact unless",
        "     one of these tools actually showed it to you.** \"I clicked Save and the item appeared\" is a",
        "     lie if the only tool you called was " + T.preview + " on a console pal — that tool cannot see the",
        "     page. If you have not observed something, say so and ask the user to check, instead of",
        "     narrating a plausible-sounding result.",
        "6. For a WEB pal page (public, crawled), also run **" + T.seo + "** after pushing — it",
        "   checks the rendered page's SEO (title/description, ABSOLUTE og: URLs, one H1, JSON-LD,",
        "   img alt text) and tells you exactly what to fix. Do not declare a public web page done",
        "   while it reports errors. (Read the seo-core skill first when it's present.)",
        "",
        "**Building a whole project?** The `pal-spec` skill interviews the user and produces",
        "SPEC.md + EXECUTION.md; the `pal-loop` skill executes them task-by-task with on-disk",
        "checkpoints. If the workspace has an EXECUTION.md with unfinished tasks, read pal-loop first.",
        "",
        "- If a push is **refused for drift** (someone saved on the server since your last pull), you have",
        "  two good options: " + T.pull + " then redo your edit, OR **" + T.merge + "** to combine your changes",
        "  with the server's automatically — files only you touched stay yours, files only they touched",
        "  come from the server, and a file BOTH sides changed is left as yours with theirs saved next to",
        "  it as `<file>.server` to reconcile by hand. After a clean merge, push again (it won't be drift-blocked).",
        "- Use " + T.status + " to see whether the server is newer and who holds the lock (it names the real owner).",
        "- If a pal is locked by someone else (or checked out by you in PalBuilder), palsync reports the",
        "  owner and refuses. Do NOT casually override: overriding may destroy unsaved work. Override requires an",
        "  exact typed `confirmOverride` phrase; tell the user to unlock and close it in PalBuilder instead.",
        "- Datasets: you can create/update their TABLES with " + T.datasets + " (define in pal.json → sync). A normal",
        "  sync never deletes data; `recreate` does and needs a typed confirmation. Dataviews/data/datalists stay",
        "  PalBuilder-provisioned (preserved, never created).",
        "- Specialized checks (the owning skill explains each): " + T.fetch + " verifies ONE web page renders",
        "  (pass `expect:[strings]`; " + T.preview + " does the same inline), " + T.specLint + " lints a SPEC.md offline",
        "  (pal-spec), " + T.regression + " runs a brownfield baseline regression check (pal-init/pal-loop). Lock",
        "  handling is automatic; use `pal_lock`/`pal_unlock` (`palsync lock`/`unlock` on the CLI) only to take or",
        "  release the pal lock by hand.",
        "",
        "### Creating new files",
        "",
        "palsync's push builds its payload from `pal.json`. To create a NEW file: write the file to disk",
        "AND append a matching entry to `pal.json` — push then ships it automatically. To EDIT an existing",
        "file, just change it on disk (no manifest edit needed).",
        "",
        "**You CAN create** (write the file + append a `pal.json` entry): pages, fragments, scripts,",
        "workflows, emails, images, styles, attachments.",
        "",
        "**Pages, fragments, scripts, and workflows — ASK FIRST.** Before creating a page/fragment/script,",
        "ask \"Should this be **console** or **web**?\" and set `palType` (`palTypeConsole`/`palTypeWeb`) — it",
        "can't be inferred from the folder. For a **workflow**, ask which type and set `workflowType` (number):",
        "web=9, console=7, library=4, transaction=2 (also: 3 transaction-system, 5 transaction-webservice,",
        "11 console-system, 12 console-webservice, 14 user, 15 tunnel). Emails/images/styles/attachments need neither.",
        "",
        "New page → `pages.entry`:",
        "```json",
        "{ \"string\": \"<filename>\", \"Page\": { \"content\": \"\", \"contentType\": \"text/html\",",
        "  \"filename\": \"<filename>\", \"palType\": \"palTypeConsole\", \"hideConsoleMenu\": false } }",
        "```",
        "New fragment → `fragments.entry` (string/filename include any subpath, e.g. `contacts/list.html`):",
        "```json",
        "{ \"string\": \"<path>\", \"Fragment\": { \"content\": \"\", \"contentType\": \"text/html\",",
        "  \"filename\": \"<path>\", \"palType\": \"palTypeConsole\", \"parseable\": false } }",
        "```",
        "New script → `scripts.entry`:",
        "```json",
        "{ \"string\": \"<filename>\", \"Script\": { \"content\": \"\", \"contentType\": \"text/javascript\",",
        "  \"filename\": \"<filename>\", \"palType\": \"palTypeConsole\", \"bookmarks\": \"\" } }",
        "```",
        "New workflow → `workflows.entry` (`workflowType` is REQUIRED — without it the push is rejected):",
        "```json",
        "{ \"string\": \"<name>.js\", \"Workflow\": { \"content\": \"\", \"contentType\": \"text/javascript\",",
        "  \"filename\": \"<name>.js\", \"workflowType\": 9 } }",
        "```",
        "Leave `content` empty — push base64-encodes the file from disk.",
        "",
        "**You CANNOT create these — they are PalBuilder-only.** Do NOT create new **documents**",
        "or **fonts**. The server rejects creating these via push and the rejection fails the ENTIRE push.",
        "If the user wants a new one, tell them to create it in **PalBuilder** first.",
        "",
        "> **palsync can still EDIT any of these once they exist in PalBuilder** — editing an existing",
        "> document, font, etc. on disk and pushing works normally. The PalBuilder-only rule is about CREATION only.",
        "",
        "### Datasets — you CAN create and update these (via " + T.datasets + ")",
        "",
        "A dataset has two parts: its DEFINITION (the schema) and its TABLE (the real storage).",
        "",
        "**The schema lives INLINE in `pal.json` `datasets.entry` — that is the ONLY place " + T.datasets + " reads.**",
        "A `datasets/<name>.json` file on disk is a pull artifact for your reference; **push and sync never read it**,",
        "so writing that file alone provisions NOTHING. Put the full schema in the `pal.json` entry below.",
        "",
        "1. Add the dataset to `pal.json` `datasets.entry` — the `Dataset.fields.DatasetField[]` array IS the schema:",
        "```json",
        "{ \"string\": \"<name>\", \"Dataset\": { \"name\": \"<name>\", \"freeform\": true, \"fields\": { \"DatasetField\": [",
        "  { \"fieldName\": \"<name>Id\", \"fieldType\": \"Primary key\" },",
        "  { \"fieldName\": \"title\", \"fieldType\": \"String\", \"fieldSize\": 100, \"notNull\": true, \"notEmpty\": true },",
        "  { \"fieldName\": \"status\", \"fieldType\": \"String\", \"fieldSize\": 20, \"indexed\": true, \"defaultValue\": \"available\" },",
        "  { \"fieldName\": \"createdAt\", \"fieldType\": \"Date\" }",
        "] }, \"indexes\": \"\" } }",
        "```",
        "   - **`\"freeform\": true` is REQUIRED** — without it the provisioned table has no per-field columns and every",
        "     column query throws `Unknown column` at runtime (the server defaults it to false). " + T.datasets + " sets it",
        "     for you if you forget, but include it. `string` and `Dataset.name` are BOTH the dataset name (camelCase,",
        "     plural — e.g. `equipment`, `users`).",
        "   - **Per-field attributes** (all optional except `fieldName`/`fieldType`): `fieldSize` (max length — String/Char",
        "     only; precision/scale for Decimal), `notNull` (value must not be null), `notEmpty` (string must not be empty —",
        "     the closest thing to a min-length; there is NO min-length attribute, enforce longer minimums in the workflow),",
        "     `indexed` (index the column — needed for a filtered/sorted column), `defaultValue` (server default when a row",
        "     omits the column), `description`. The `\"Primary key\"` field maps to the platform row id — you still query it",
        "     by its `fieldName` once `freeform` is true.",
        "   - Give every dataset ONE `\"Primary key\"` field named `<name>Id`. Mark an indexed column `\"indexed\": true`.",
        "   - **Valid `fieldType` values** (EXACT strings — `\"Integer\"`/`\"int\"` are WRONG; the integer type is",
        "     `\"Number\"`): `\"Primary key\"`, `\"String\"` (needs `fieldSize`), `\"Char\"`, `\"Text\"`, `\"Boolean\"`,",
        "     `\"Number\"` (integer), `\"Big Number\"` (64-bit), `\"Decimal\"`, `\"Date\"`, `\"DateOnly\"`, `\"File\"`, `\"Encrypted\"`.",
        "     (" + T.validate + " warns on a bad type.)",
        "2. Then call **" + T.datasets + "** — it saves the pal (shipping the definition) and provisions the actual table.",
        "   Adding the entry ALONE never creates the table; the sync step is what builds it. **Skipping sync means every",
        "   `pal.getDataSet(\"<name>\")` in your workflow hits a table that does not exist — reads return nothing, writes",
        "   silently fail.** After sync, verify with " + T.test + ".",
        "- A normal sync is SAFE: it creates the table if missing and applies additive changes, never deleting data.",
        "- `recreate` DROPS and rebuilds a table, DELETING ALL ITS ROWS. It requires an exact typed confirmation",
        "  and must never be used to make an additive change. Only suggest recreate when a column type must change",
        "  or a column is removed, and always warn the user it deletes all data first.",
        "- `dataviews`, `data`, `datalists` are still PalBuilder-provisioned — push/pull preserve them, don't create them.",
        "",
        "PalBuilder coding rules are in the **PalBuilder Agent Rules** section above; deeper reference lives in the skills in `.claude/skills/` — read them before writing pal code: `palbuilder-core` (platform foundations, ES3 rules, `pal.json`), `palbuilder-data` (datasets, payloads, HTTP), `palbuilder-frontend` (pages/fragments/`c:` tags), `palbuilder-backend` (workflow `run()` code), `palbuilder-jobs-http` (background jobs)."
    ].join("\n");
}

// The single palsync-owned doc: the static PalBuilder coding contract (bundled CLAUDE.md) + the
// templated sync-etiquette/creation/dataset rules, under one version stamp. Written byte-for-byte to
// CLAUDE.palsync.md (and inlined into AGENTS.md for codex/pi) — regenerated wholesale every setup, so
// the rules live in ONE place and cannot drift between two files.
async function buildPalsyncDoc(palName, opts) {
    const contract = (await fs.readFile(path.join(BUNDLE_DIR, "CLAUDE.md"), "utf8")).trim();
    return [stampComment(), "", contract, "", "---", "", syncSection(palName, opts)].join("\n") + "\n";
}

// CLAUDE.md managed block (Claude): a REAL `@import` of the owned doc — must be on its own line and
// NOT inside backticks, or Claude Code's import parser skips it (it ignores code spans). Tiny + stable:
// only the stamp changes between versions, so re-inject never churns the user's surrounding prose.
function importBlock() {
    return [BEGIN,
        stampComment(),
        "PalBuilder rules for this pal are maintained by palsync in `CLAUDE.palsync.md` and loaded via",
        "the import below. It is regenerated on each `palsync` launch — edit it only through palsync.",
        "",
        "@CLAUDE.palsync.md",
        END].join("\n");
}

// AGENTS.md managed block (codex/pi): the FULL doc inlined. Those agents read AGENTS.md natively but
// their `@import` support is unreliable, so the rules go in directly rather than via a reference.
function agentsBlock(doc) {
    return BEGIN + "\n" + doc.trimEnd() + "\n" + END;
}

// Insert or replace the managed block, preserving all user content outside the markers.
function mergeManaged(existing, block) {
    if (existing == null) {
        return { content: block + "\n", mode: "created" };
    }
    const b = existing.indexOf(BEGIN);
    const e = existing.indexOf(END);
    if (b !== -1 && e !== -1 && e > b) {
        // Replace existing managed region in place; keep everything else verbatim.
        const before = existing.slice(0, b);
        const after = existing.slice(e + END.length);
        return { content: before + block + after, mode: "refreshed" };
    }
    // Append the block, preserving the user's existing content above it.
    const sep = existing.endsWith("\n") ? "\n" : "\n\n";
    return { content: existing + sep + block + "\n", mode: "appended" };
}

async function copyFile(src, dest) {
    await fs.mkdir(path.dirname(dest), { recursive: true });
    await fs.copyFile(src, dest);
}

async function readIfExists(p) {
    try { return await fs.readFile(p, "utf8"); }
    catch (e) { if (e.code === "ENOENT") return null; throw e; }
}

// Discover every skill shipped in the bundle: each subdir of bundled-context/skills/ that has a
// SKILL.md, normalized to { name, assets } where assets are the files under its references/
// (auto-shipped). The bundle dir is the single source of truth — no list to keep in sync with disk.
async function bundledSkills() {
    const skillsRoot = path.join(BUNDLE_DIR, "skills");
    let entries;
    try { entries = await fs.readdir(skillsRoot, { withFileTypes: true }); }
    catch (e) { if (e.code === "ENOENT") return []; throw e; }
    const out = [];
    for (const ent of entries) {
        if (!ent.isDirectory()) continue;
        const dir = path.join(skillsRoot, ent.name);
        try { await fs.access(path.join(dir, "SKILL.md")); }
        catch (e) { continue; } // a dir without SKILL.md is not a skill — skip it
        let assets = [];
        try {
            const refs = await fs.readdir(path.join(dir, "references"), { withFileTypes: true });
            assets = refs.filter(r => r.isFile()).map(r => path.join("references", r.name));
        } catch (e) { /* no references/ — SKILL.md-only skill */ }
        out.push({ name: ent.name, assets });
    }
    return out;
}

// Copy a skill set's SKILL.md (+ companion assets) into <rootDir>/skills/<name>/.
// rootDir is the agent's skills root: ".claude" (Claude) or ".agents" (Codex open standard).
async function copySkillSet(workspaceDir, rootDir, skills) {
    for (const s of skills) {
        await copyFile(path.join(BUNDLE_DIR, "skills", s.name, "SKILL.md"),
                       path.join(workspaceDir, rootDir, "skills", s.name, "SKILL.md"));
        for (const asset of (s.assets || [])) {
            await copyFile(path.join(BUNDLE_DIR, "skills", s.name, asset),
                           path.join(workspaceDir, rootDir, "skills", s.name, asset));
        }
    }
}

// Every skill name palsync owns (current + retired). Used by pruneSkills to know which dirs are safe
// to remove — anything outside this set is a user-added skill and is left alone.
async function ownedSkillNames() {
    const names = (await bundledSkills()).map(s => s.name);
    return new Set([...names, ...RETIRED_SKILLS]);
}

// Remove palsync-owned skill dirs that are NOT in the effective set for this session (a skill that was
// dropped from always-on, renamed, or retired). copySkillSet only adds; without this the set only grows
// and stale skills linger forever. Returns the names removed.
async function pruneSkills(workspaceDir, rootDir, keepNames) {
    const skillsDir = path.join(workspaceDir, rootDir, "skills");
    let entries;
    try { entries = await fs.readdir(skillsDir, { withFileTypes: true }); }
    catch (e) { if (e.code === "ENOENT") return []; throw e; }
    const keep = new Set(keepNames);
    const owned = await ownedSkillNames();
    const removed = [];
    for (const ent of entries) {
        if (!ent.isDirectory()) continue;
        if (owned.has(ent.name) && !keep.has(ent.name)) {
            await fs.rm(path.join(skillsDir, ent.name), { recursive: true, force: true });
            removed.push(ent.name);
        }
    }
    return removed;
}

// Remove a workspace's managed block from a file, preserving any user content outside the markers.
// Deletes the file outright if nothing but whitespace remains. No-op if the file or block is absent.
async function stripManaged(filePath) {
    const existing = await readIfExists(filePath);
    if (existing == null) return false;
    const b = existing.indexOf(BEGIN), e = existing.indexOf(END);
    if (b === -1 || e === -1 || e <= b) return false;
    const rest = existing.slice(0, b) + existing.slice(e + END.length);
    if (rest.trim() === "") { await fs.rm(filePath, { force: true }); return true; }
    await fs.writeFile(filePath, rest, "utf8");
    return true;
}

// A workspace carries files for ONE agent — the one it was last launched with. When the selected agent
// isn't Claude, remove the Claude-owned artifacts (and vice-versa) so a Pi/Codex pal isn't littered with
// dead CLAUDE.* files and duplicate .claude/skills. Only palsync-owned content is touched; user notes in
// CLAUDE.md/AGENTS.md and user-authored skills survive.
// Remove a dir only if it is now empty (rmdir fails with ENOTEMPTY otherwise) — so an emptied
// .claude/skills (and .claude itself) goes, but a dir still holding user settings is left alone.
async function rmDirIfEmpty(dir) {
    try { await fs.rmdir(dir); return true; } catch (e) { return false; }
}
async function pruneAgentRoot(workspaceDir, rootDir) {
    const removed = await pruneSkills(workspaceDir, rootDir, []);
    await rmDirIfEmpty(path.join(workspaceDir, rootDir, "skills"));
    await rmDirIfEmpty(path.join(workspaceDir, rootDir));
    return removed;
}
async function cleanClaudeArtifacts(workspaceDir) {
    await fs.rm(path.join(workspaceDir, "CLAUDE.palsync.md"), { force: true });
    await stripManaged(path.join(workspaceDir, "CLAUDE.md"));
    return pruneAgentRoot(workspaceDir, ".claude");
}
async function cleanAgentsArtifacts(workspaceDir) {
    await stripManaged(path.join(workspaceDir, "AGENTS.md"));
    return pruneAgentRoot(workspaceDir, ".agents");
}

// Read the version stamp off whichever owned doc this workspace carries (CLAUDE.palsync.md for Claude,
// AGENTS.md for Codex/Pi) and compare to the installed build. `palsync status` uses this to flag a
// workspace that predates the current build (relaunch refreshes it).
async function contextStatus(workspaceDir) {
    for (const file of ["CLAUDE.palsync.md", "AGENTS.md"]) {
        const txt = await readIfExists(path.join(workspaceDir, file));
        if (txt == null) continue;
        const m = txt.match(STAMP_RE);
        const version = m ? m[1] : null;
        return { present: true, file, version, current: VERSION, stale: version !== VERSION };
    }
    return { present: false, file: null, version: null, current: VERSION, stale: true };
}

// Inject context into workspaceDir for the SELECTED agent only, and clean the other agent's
// palsync-owned artifacts so a workspace carries exactly the files its agent reads.
//   claude → .claude/skills + CLAUDE.palsync.md (the owned doc) + a tiny CLAUDE.md block that
//            `@CLAUDE.palsync.md`-imports it. Claude Code reads CLAUDE.md and resolves the import.
//   codex/pi/opencode → .agents/skills + AGENTS.md carrying the full doc inline (their @import
//            support is unreliable; Claude Code does not read .agents/ or AGENTS.md — verified).
//            Pi uses the CLI flavor (palsync subcommands, no session lock); Codex and OpenCode use
//            the MCP flavor (both get a registered MCP server — see workspace.js).
async function inject(workspaceDir, { palName, agent = "claude" } = {}) {
    const skills = await bundledSkills();
    const keep = skills.map(s => s.name);
    const skillNames = keep.slice();

    if (agent === "codex" || agent === "pi" || agent === "opencode") {
        await copySkillSet(workspaceDir, ".agents", skills);
        const prunedAgents = await pruneSkills(workspaceDir, ".agents", keep);
        const agentsDoc = await buildPalsyncDoc(palName, { cli: agent === "pi" });
        const agentsPath = path.join(workspaceDir, "AGENTS.md");
        const existingAgents = await readIfExists(agentsPath);
        const mergedAgents = mergeManaged(existingAgents, agentsBlock(agentsDoc));
        await fs.writeFile(agentsPath, mergedAgents.content, "utf8");
        const cleanedClaude = await cleanClaudeArtifacts(workspaceDir);
        return {
            agent,
            skills: [],
            agentSkills: skillNames.map(name => path.join(".agents/skills", name, "SKILL.md")),
            agentsMd: { path: "AGENTS.md", mode: mergedAgents.mode, userContentPreserved: existingAgents != null },
            prunedSkills: prunedAgents,
            cleanedClaudeSkills: cleanedClaude,
            version: VERSION
        };
    }

    // Claude (default).
    await copySkillSet(workspaceDir, ".claude", skills);
    const prunedClaude = await pruneSkills(workspaceDir, ".claude", keep);
    await fs.writeFile(path.join(workspaceDir, "CLAUDE.palsync.md"),
        await buildPalsyncDoc(palName, { cli: false }), "utf8");
    const claudePath = path.join(workspaceDir, "CLAUDE.md");
    const existingClaude = await readIfExists(claudePath);
    const mergedClaude = mergeManaged(existingClaude, importBlock());
    await fs.writeFile(claudePath, mergedClaude.content, "utf8");
    const cleanedAgents = await cleanAgentsArtifacts(workspaceDir);
    return {
        agent,
        skills: skillNames.map(name => path.join(".claude/skills", name, "SKILL.md")),
        agentSkills: [],
        claudePalsync: "CLAUDE.palsync.md",
        claudeMd: { path: "CLAUDE.md", mode: mergedClaude.mode, userContentPreserved: existingClaude != null },
        prunedSkills: prunedClaude,
        cleanedAgentsSkills: cleanedAgents,
        version: VERSION
    };
}

module.exports = { inject, mergeManaged, importBlock, agentsBlock, buildPalsyncDoc, syncSection,
    pruneSkills, stripManaged, cleanClaudeArtifacts, cleanAgentsArtifacts, contextStatus,
    BEGIN, END, BUNDLE_DIR, VERSION, bundledSkills, ownedSkillNames };
