"use strict";
// Inject bundled PalBuilder context into a pal workspace WITHOUT clobbering user content.
//   - .claude/skills/<name>/SKILL.md  (copied from bundle; palsync-owned, progressive-disclosure depth)
//   - .opencode/commands/<name>.md     (OpenCode only; slash-command wrapper that loads the skill)
//   - CLAUDE.palsync.md  = the SINGLE palsync-owned doc: the static coding contract (bundled CLAUDE.md)
//                          + the templated sync/creation/dataset rules, under one version stamp.
//                          Regenerated wholesale each setup, so the rules live in ONE file and can't
//                          drift between two.
//   - CLAUDE.md          = the user's file, with a tiny managed block that `@CLAUDE.palsync.md`-imports
//                          the owned doc. The import is on its own line and un-backticked — Claude
//                          Code's import parser skips code spans, so a backticked @ref would NOT load.
// Re-running setup rewrites the owned doc + the managed block + prunes retired skills; a teammate's own
// CLAUDE.md notes (outside the markers) survive. `contextStatus()` compares the doc's stamp to the
// installed build so `palsync status` can flag a workspace that needs a relaunch to refresh.
const fs = require("fs/promises");
const path = require("path");
const { writeIfChanged } = require("../core/atomicWrite");
const claudeHooks = require("./claudeHooks");
let workspaceIgnoreSync = null;
function getWorkspaceIgnoreSync() {
    if (!workspaceIgnoreSync) {
        try { workspaceIgnoreSync = require("../core/workspaceIgnore"); } catch (e) { workspaceIgnoreSync = null; }
    }
    return workspaceIgnoreSync;
}

const BUNDLE_DIR = path.join(__dirname, "..", "..", "bundled-context");
const VERSION = require("../../package.json").version;
const SHARED_REFERENCES = "shared";

// Stamp the owned doc with the palsync version that generated it, so `palsync status` can flag a
// workspace whose context predates the installed build (relaunch re-injects and refreshes it).
const STAMP_RE = /<!--\s*palsync-context\s+v([0-9][^\s]*)/;
function stampComment() {
    return "<!-- palsync-context v" + VERSION + " — regenerated by palsync setup; do not edit by hand -->";
}

// Skill dir names palsync has shipped but later renamed/removed. Pruned from a workspace if present
// so a re-inject drops them (e.g. design-core → design-system-init + design-build). User-added skills
// (names palsync never owned) are never touched.
const RETIRED_SKILLS = [
    "design-core",
    "palbuilder-design",
    "design",
    "palbuilder-jobs-http",
    "palbuilder-websockets",
    "pal-restraint",
    "palbuilder-backend",
    "seo-core"
];

// Every skill in the bundle loads every session — the bundle dir IS the inventory, discovered at
// inject time (see bundledSkills), so a newly-added skill ships automatically with no hand-kept
// list to drift out of sync. Skills cost no context until the agent opens one (only their
// name+description are read at startup); each skill's references/* ride along so a SKILL.md that
// links them always has them in the workspace.
const BEGIN = "<!-- >>> palsync managed block — do not edit; regenerated by palsync setup >>> -->";
const END = "<!-- <<< palsync managed block <<< -->";
const OPENCODE_COMMAND_MARKER = "<!-- palsync managed OpenCode skill command; regenerated by palsync setup -->";

// The sync-etiquette section that teaches the agent the palsync workflow (decision: conversational).
// cli=true renders the Pi flavor: palsync CLI subcommands instead of MCP tools, and lock-per-command
// instead of an always-on session lock (Pi has no MCP — it drives palsync through its shell CLI).
function syncDetails(palName, { cli = false, skillsDir = ".claude/skills" } = {}) {
    const T = cli
        ? { pull: "`palsync pull`", push: "`palsync push`", validate: "`palsync validate`",
            test: "`palsync test`", preview: "`palsync preview`", open: "`palsync open`", seo: "`palsync seo-audit`",
            merge: "`palsync merge`", status: "`palsync status`", datasets: "`palsync sync-datasets`",
            screenshot: "`palsync screenshot`", fetch: "`palsync fetch`", specLint: "`palsync spec-lint`",
            regression: "`palsync regression`", exercise: "`palsync exercise`", skip: "the `--skip-validation` flag" }
        : { pull: "`pal_pull`", push: "`pal_push`", validate: "`pal_validate`",
            test: "`pal_test`", preview: "`pal_preview`", seo: "`pal_seo_audit`",
            merge: "`pal_merge`", status: "`pal_status`", datasets: "`pal_sync_datasets`",
            screenshot: "`pal_screenshot`", fetch: "`pal_fetch`", specLint: "`pal_spec_lint`",
            regression: "`pal_regression`", exercise: "`pal_exercise`" };
    const conn = cli
        ? "This pal" + (palName ? " (**" + palName + "**)" : "") + " is connected to CloudPiston via the **palsync CLI** — run its subcommands in your shell (e.g. `palsync push`, `palsync pull`). palsync takes the pal lock for each push/pull and releases it; there is no always-on session lock."
        : "This pal" + (palName ? " (**" + palName + "**)" : "") + " is connected to CloudPiston via the **palsync** MCP server and is **locked for your session**.";
    return [
        "## palsync — sync etiquette (managed)",
        "",
        conn,
        "",
        "**Load every skill the task touches before writing any pal code** — see the Platform",
        "skills list above. PalBuilder is a proprietary dialect you do NOT know from training —",
        "your defaults (object literals, `let`/`const`, normal HTML habits) produce code that",
        "saves but then FAILS to compile or render. The skills are the rules; follow them literally.",
        "**Visible UI has a mandatory two-skill route:** for every page, fragment, form, table,",
        "navigation, or browser-side UI change, load both `palbuilder-frontend` (platform syntax) and",
        "`design-build` (UX and visual quality) before coding. If real `DESIGN_SYSTEM.md` /",
        "`COMPONENTS.md` files are absent, load `design-system-init` first. A compile pass is not a",
        "design pass: render desktop and mobile, inspect the pixels plus `designAudit`, fix the",
        "highest-impact failures, and re-render before calling visible work done.",
        ...(skillsDir === ".claude/skills" ? [] : [
        "**Load skills through your skill tool, by name/description — never additionally Read/cat a",
        "file under `" + skillsDir + "/`.** The skill tool already loads a skill's full body; reading",
        "the file too puts the same text in context twice.",
        ]),
        "",
        "The working loop:",
        "",
        ...(cli ? [] : [
            "**Testing:** User says stop/resume testing → call `pal_testing` with `enabled:false`/`true`.",
            "Do not retry skipped checks or report them as passed; validate and push validation stay on.",
            ""
        ]),
        "1. " + T.pull + " before starting significant work. Pull is a safe sync: it preserves NEW",
        "   un-pushed files (and carries their `pal.json` entries forward), and it REFUSES — naming",
        "   the files — if it would overwrite un-pushed local edits.",
        "2. Write code following the skills. " + T.validate + " is an instant offline check that",
        "   catches the known PalBuilder breakers (object literals in workflows, `let`/`const`,",
        "   unclosed void tags, undocumented `c:` attributes, `${}` in inline scripts) — use it to",
        "   diagnose BETWEEN edits, but do NOT run it right before a push: push runs the same",
        "   validation itself, so validate-then-push is a wasted round trip.",
        "3. **Offer to " + T.push + "** when a meaningful change is done (palsync does not auto-push).",
        "   Push runs the full validation as its gate and refuses on errors YOUR change introduced — fix",
        "   every one; each finding says exactly how; fix warnings too, or checkpoint why each is safe",
        "   before marking the task done. There is no bypass" + (cli ? " you should use (" + T.skip + " exists for humans only)" : "") + ". (Pre-existing errors",
        "   in a file you edit don't block you; only new ones do.)",
        "4. After pushing workflow or UI changes, **offer to " + T.test + "** — it runs the SERVER's own",
        "   validation. In auto mode it does NOT open the user's browser; open a live preview only at a",
        "   human-review stop (" + (cli ? "`palsync test --preview` or " + T.open : "`pal_test` with `preview:true`") + ").",
        "5. **" + T.validate + " and " + T.test + " only prove the code COMPILES — not that it RENDERS.** A",
        "   workflow that validates can still THROW at runtime (bad SQL, a null, a column the table lacks)",
        "   and paint an error block instead of the UI. You MUST call **" + T.screenshot + "** after every push",
        "   that touches a page/fragment/workflow, and see a clean capture, before declaring that change",
        "   done — not optional, not \"if you have time.\" " + T.preview + " (CONSOLE/transaction) does not open",
        "   by default; when explicitly opened for human review, it only shows the USER, not YOU. " + T.screenshot + " is different:",
        "   it drives an authenticated console screen too (replays the auth redirect chain in a headless",
        "   browser) and returns a PNG + a `renderError` if the workflow threw. For a WEB pal, " + T.fetch + "/",
        "   " + T.preview + " with `expect:[strings]` also count as verification. Only fall back to asking the",
        "   user to eyeball the screen themselves if the check tool reports itself unavailable (no Chromium,",
        "   or the auth replay failed) — never as a substitute for calling it. Preview/screenshot/fetch show",
        "   the LAST PUSHED version, so push before checking your latest edits.",
        "   - **Never report page content, saved data, or a completed click/type/submit flow as fact unless",
        "     one of these tools actually showed it to you** (see PalBuilder Agent Rules → Anti-patterns,",
        "     \"Narrating UI you did not observe\", above).",
        "6. For a WEB pal page (public, crawled), also run **" + T.seo + "** after pushing — it",
        "   checks the rendered page's SEO (title/description, ABSOLUTE og: URLs, one H1, JSON-LD,",
        "   img alt text) and tells you exactly what to fix. Do not declare a public web page done",
        "   while it reports errors. (Read the palbuilder-seo skill first when it's present.)",
        "",
        "**Building a whole project?** The `pal-spec` skill interviews the user and produces",
        "SPEC.md + EXECUTION.md; the `pal-loop` skill executes them task-by-task with on-disk",
        "checkpoints. If the workspace has an EXECUTION.md with unfinished tasks, read pal-loop first.",
        "",
        "- If a push is **refused for drift** (someone saved on the server since your last pull), you have",
        "  two good options: " + T.pull + " then redo your edit, OR **" + T.merge + "** to combine your changes",
        "  with the server's automatically — files only you touched stay yours, files only they touched",
        "  come from the server, and a file BOTH sides changed is left as yours with theirs saved next to",
        "  it as `<file>.server` to reconcile by hand. After a clean merge, push again (it won't be drift-blocked).",
        "- Use " + T.status + " to see whether the server is newer and who holds the lock (it names the real owner).",
        "- If a pal is locked by someone else (or checked out by you in PalBuilder), palsync reports the",
        "  owner and refuses. Do NOT casually override: overriding may destroy unsaved work. Override requires an",
        "  exact typed `confirmOverride` phrase; tell the user to unlock and close it in PalBuilder instead.",
        "- Datasets: you can create/update their TABLES with " + T.datasets + " (define in pal.json → sync). A normal",
        "  sync never deletes data; `recreate` does and needs a typed confirmation. Data/dataList/DataView manifest",
        "  entries stay PalBuilder-provisioned, not created by push. Workflows may build a runtime DataView with `pal.createDataViewBuilder()`;",
        "  see palbuilder-data/references/dataviews.md.",
        ...(cli ? [] : [
        "- **Never run `palsync` SYNC commands from your shell in this session** (push/pull/status/",
        "  validate/test/…) — the pal_* tools above ARE the interface, and the bare `palsync` command",
        "  opens an interactive human launcher. The ONLY shell exceptions are the OFFLINE local helpers",
        "  with no MCP equivalent: `palsync task …`, `palsync checkpoint …`, and the offline",
        "  `palsync review check` completion gate (pal-loop/pal-review use these; they touch no",
        "  server). And **NEVER `pkill`/`kill` anything matching",
        "  `palsync`** — that kills this session's own MCP server and every pal_* tool with it. If a",
        "  tool seems missing, ask the user; do not fall back to the CLI.",
        ]),
        ...(cli ? [] : [
        "- **Tunnel workflows (workflowType 15)** are the pal's web-service surface, and `pal_tunnel_test`",
        "  is how you test one for REAL: it calls the workflow and returns its actual JSON response — real",
        "  data, not a compile verdict. When the user says \"test tunnel [name]\", ask (unless already",
        "  clear): the **action** to send (optional), the **workflow** if the pal has several tunnels (the",
        "  tool result lists them; default = the registered one), and the **payload** — none, inline JSON",
        "  they give you, or a JSON file path (`payloadFile`). Credentials are handled automatically. It",
        "  runs the LAST PUSHED version (push first); an empty response means the workflow threw at runtime.",
        "- **Server-side debugging — use it instead of guessing.** `c.debug(...)` output from any executed",
        "  workflow comes back AUTOMATICALLY as a \"server debug\" block on `pal_tunnel_test` / `pal_fetch` /",
        "  `pal_preview` (web) / `pal_screenshot` results; `pal_debug` retrieves it manually (e.g. after",
        "  a human-review browser preview ran). When diagnosing a runtime fault, add `c.debug` lines to the",
        "  workflow, push, re-run the check, read the debug block — then REMOVE the instrumentation before",
        "  declaring the work done. The buffer is consume-once and SHARED with the PalBuilder IDE's debug",
        "  view: reading it clears it for everyone, so mention that if the user is also watching PalBuilder.",
        ]),
        "- Specialized checks (the owning skill explains each): " + T.fetch + " verifies ONE web page renders",
        "  (pass `expect:[strings]`; " + T.preview + " does the same inline), " + T.exercise + " EXERCISES a workflow",
        "  action end-to-end and asserts `expect`/`absent` strings in the result (the check for \"did the write",
        "  actually work\" — after building any create/edit/delete action, run it; after an edit put the OLD value",
        "  in `absent` to catch a duplicate insert; after a delete put the deleted name in `absent`, never",
        "  empty-state text), " + T.specLint + " lints a SPEC.md offline",
        "  (pal-spec), " + T.regression + " runs a brownfield baseline regression check (pal-init/pal-loop). Lock",
        "  handling is automatic; use `pal_lock`/`pal_unlock` (`palsync lock`/`unlock` on the CLI) only to take or",
        "  release the pal lock by hand.",
        "",
        "### Creating new files",
        "",
        "Push builds from `pal.json`. For a NEW file, write it and append its matching manifest entry.",
        "",
        "**You CAN create** pages, fragments, scripts, workflows, emails, images, styles, attachments,",
        "wizards, and documents (write the file + add its `pal.json` entry). **Fonts are the one",
        "PalBuilder-only exception** — the server rejects a new font outright and fails the whole push;",
        "if the user wants a new font, tell them to add it in PalBuilder first. You CAN still edit any",
        "existing font on disk and push that normally.",
        "",
        "**ASK FIRST:** page/fragment/script needs console or web, then `palTypeConsole` or `palTypeWeb`.",
        "Workflow needs its numeric type: web=9, console=7, library=4, transaction=2, transaction-system=3,",
        "transaction-webservice=5, console-system=11, console-webservice=12, user=14, tunnel=15.",
        "Document needs its contentType: `text/html` or `application/pdf`.",
        "Emails/images/styles/attachments/wizards need neither field.",
        "",
        "New page → `pages.entry`:",
        "```json",
        "{ \"string\": \"<filename>\", \"Page\": { \"content\": \"\", \"contentType\": \"text/html\",",
        "  \"filename\": \"<filename>\", \"palType\": \"palTypeConsole\", \"hideConsoleMenu\": false } }",
        "```",
        "New fragment → `fragments.entry` (string/filename include any subpath, e.g. `contacts/list.html`):",
        "```json",
        "{ \"string\": \"<path>\", \"Fragment\": { \"content\": \"\", \"contentType\": \"text/html\",",
        "  \"filename\": \"<path>\", \"palType\": \"palTypeConsole\", \"parseable\": false } }",
        "```",
        "Before first push, write at least `<c:ignore xmlns:c=\"contractpal\"></c:ignore>` to the fragment file;",
        "an empty fragment file fails `Fragment content is missing`. Manifest `content` stays empty; push fills it from disk.",
        "New script → `scripts.entry`:",
        "```json",
        "{ \"string\": \"<filename>\", \"Script\": { \"content\": \"\", \"contentType\": \"text/javascript\",",
        "  \"filename\": \"<filename>\", \"palType\": \"palTypeConsole\", \"bookmarks\": \"\" } }",
        "```",
        "New workflow → `workflows.entry` (`workflowType` is REQUIRED — without it the push is rejected):",
        "```json",
        "{ \"string\": \"<name>.js\", \"Workflow\": { \"content\": \"\", \"contentType\": \"text/javascript\",",
        "  \"filename\": \"<name>.js\", \"workflowType\": 9 } }",
        "```",
        "Leave `content` empty — push base64-encodes the file from disk.",
        "New wizard → `wizards.entry` (content is the wizard's `<dialogs>` XHTML — see",
        "`palbuilder-core/references/pal-structure.md`; no client-side validation is done on it):",
        "```json",
        "{ \"string\": \"<name>.xml\", \"Wizard\": { \"content\": \"\", \"contentType\": \"text/html\",",
        "  \"filename\": \"<name>.xml\" } }",
        "```",
        "New document → `documents.entry` (see `palbuilder-workflow/references/documents.md` for the",
        "workflow API, field/signature shapes, and the `c:document` tag). For a new HTML document,",
        "copy `palbuilder-workflow/references/templates/document-html.html` with bash `cp` (never",
        "read-then-write) — it needs the FULL DOM (html/head/body), not a bare content div, and",
        "shows every field/signature form (`${field:...}`, `${signature:...}`, explicit `cp-sig-*`",
        "attributes, `cp-target`) with no `pal.json` authoring required for any of them. A PDF",
        "document's field/signature `x`/`y`/`width`/`height`/`page` coordinates come from the",
        "PalBuilder designer instead — never hand-guess them; say so if you need one placed and",
        "don't have designer access:",
        "```json",
        "{ \"string\": \"<filename>\", \"Document\": { \"content\": \"\", \"contentType\": \"text/html\",",
        "  \"filename\": \"<filename>\" } }",
        "```",
        "",
        "### Datasets — you CAN create and update these (via " + T.datasets + ")",
        "",
        "A dataset has two parts: its DEFINITION (the schema) and its TABLE (the real storage).",
        "",
        "**The schema lives INLINE in `pal.json` `datasets.entry` — that is the ONLY place " + T.datasets + " reads.**",
        "A `datasets/<name>.json` file on disk is a pull artifact for your reference; **push and sync never read it**,",
        "so writing that file alone provisions NOTHING. Put the full schema in the `pal.json` entry below.",
        "",
        "1. Add the dataset to `pal.json` `datasets.entry` — the `Dataset.fields.DatasetField[]` array IS the schema:",
        "```json",
        "{ \"string\": \"<name>\", \"Dataset\": { \"name\": \"<name>\", \"freeform\": true, \"fields\": { \"DatasetField\": [",
        "  { \"fieldName\": \"<name>Id\", \"fieldType\": \"Primary key\" },",
        "  { \"fieldName\": \"title\", \"fieldType\": \"String\", \"fieldSize\": 100, \"notNull\": true, \"notEmpty\": true },",
        "  { \"fieldName\": \"status\", \"fieldType\": \"String\", \"fieldSize\": 20, \"indexed\": true, \"defaultValue\": \"available\" },",
        "  { \"fieldName\": \"createdAt\", \"fieldType\": \"Date\" }",
        "] }, \"indexes\": \"\" } }",
        "```",
        "   - **`\"freeform\": true` is REQUIRED** — without it the provisioned table has no per-field columns and every",
        "     column query throws `Unknown column` at runtime (the server defaults it to false). " + T.datasets + " sets it",
        "     for you if you forget, but include it. `string` and `Dataset.name` are BOTH the dataset name (camelCase,",
        "     plural — e.g. `equipment`, `users`).",
        "   - **Per-field attributes** (all optional except `fieldName`/`fieldType`): `fieldSize` (max length — String/Char",
        "     only; precision/scale for Decimal), `notNull` (value must not be null), `notEmpty` (string must not be empty —",
        "     the closest thing to a min-length; there is NO min-length attribute, enforce longer minimums in the workflow),",
        "     `indexed` (index the column — needed for a filtered/sorted column), `defaultValue` (server default when a row",
        "     omits the column), `description`. The `\"Primary key\"` field maps to the platform row id — you still query it",
        "     by its `fieldName` once `freeform` is true.",
        "   - Give every dataset ONE `\"Primary key\"` field named `<name>Id`. Mark an indexed column `\"indexed\": true`.",
        "   - **Valid `fieldType` values** (EXACT strings — `\"Integer\"`/`\"int\"` are WRONG; the integer type is",
        "     `\"Number\"`): `\"Primary key\"`, `\"String\"` (needs `fieldSize`), `\"Char\"`, `\"Text\"`, `\"Boolean\"`,",
        "     `\"Number\"` (integer), `\"Big Number\"` (64-bit), `\"Decimal\"`, `\"Date\"`, `\"DateOnly\"`, `\"File\"`, `\"Encrypted\"`.",
        "     (" + T.validate + " warns on a bad type.)",
        "2. Then call **" + T.datasets + "** — it saves the pal (shipping the definition) and provisions the actual table.",
        "   Adding the entry ALONE never creates the table; the sync step is what builds it. **Skipping sync means every",
        "   `pal.getDataSet(\"<name>\")` in your workflow hits a table that does not exist — reads return nothing, writes",
        "   silently fail.** After sync, verify with " + T.test + ".",
        "- A normal sync is SAFE: it creates the table if missing and applies additive changes, never deleting data.",
        "- `recreate` DROPS and rebuilds a table, DELETING ALL ITS ROWS. It requires an exact typed confirmation",
        "  and must never be used to make an additive change. Only suggest recreate when a column type must change",
        "  or a column is removed, and always warn the user it deletes all data first.",
        "- " + T.datasets + " provisions DataSet tables only. A DataView is a read-only join/read model, not a table;",
        "  DataViews/data/datalists stay PalBuilder-created, and push/pull only preserves them."
    ].join("\n");
}

function syncSection(palName, { cli = false, skillsDir = ".claude/skills" } = {}) {
    const T = cli
        ? { pull: "`palsync pull`", push: "`palsync push`", validate: "`palsync validate`", test: "`palsync test`", screenshot: "`palsync screenshot`" }
        : { pull: "`pal_pull`", push: "`pal_push`", validate: "`pal_validate`", test: "`pal_test`", screenshot: "`pal_screenshot`" };
    return [
        "## palsync — essential sync contract (managed)",
        "",
        "This pal" + (palName ? " (**" + palName + "**)" : "") + " is connected to CloudPiston through " + (cli ? "the palsync CLI; locks are per-command." : "the palsync MCP server and is locked for your session."),
        "",
        "Load every skill the task touches before writing PalBuilder code. For visible UI, load",
        "Visible UI has a mandatory two-skill route: load both `palbuilder-frontend` and `design-build`;",
        "load `design-system-init` first when design-system files are absent. Render desktop and mobile,",
        "inspect pixels and `designAudit`, then fix failures. " + (skillsDir === ".claude/skills" ? "" : "Load skills through the skill tool; never additionally Read/cat files under `" + skillsDir + "`.").trim(),
        "",
        "**Call `pal_context` when the task touches sync, file creation, or datasets** — it returns",
        "the detailed contract this summary is built from. No arguments lists the available",
        "sections; pass `section:\"sync-workflow\"`, `section:\"creating-files\"`, or",
        "`section:\"datasets\"` (or a `query`) to load the one you need before those operations.",
        "",
        "Working loop:",
        "1. " + T.pull + " before significant work; it refuses rather than overwrite local edits.",
        "2. Follow the owning skills. Use " + T.validate + " between edits, not immediately before push.",
        "3. Offer " + T.push + " once per meaningful change. Push validates and has no agent bypass.",
        "4. After workflow/UI pushes, run " + T.test + " for server compile and " + T.screenshot + " for",
        "   actual render evidence. Compile success never proves the UI rendered or behavior worked.",
        "5. Runtime checks inspect the last pushed version. Never narrate UI/data a tool did not show.",
        "6. Completion gate: after a fresh reviewer overwrites `REVIEW.md`, run `palsync completion check`.",
        "   Missing/stale review evidence or a non-PASS result means the build is not done. Claude",
        "   blocks Stop, Pi queues a corrective follow-up, and other harnesses call this CLI manually.",
        "",
        "Use `pal_context` for the detailed `sync-workflow`, `creating-files`, or `datasets` contract",
        "before those operations. It includes drift/lock handling, browser/runtime verification, exact",
        "pal.json entries, creatable-file limits, dataset schemas, and destructive-sync rules.",
        ...(cli ? [
            "",
            "CLI tools: `palsync push`, `palsync pull`, `palsync validate`, `palsync test`,",
            "`palsync screenshot`, `palsync sync-datasets`. Do not use validation-skip flags."
        ] : [
            "",
            "Use `pal_testing` when the user stops/resumes tests. Never run palsync sync commands in the",
            "shell while MCP tools are active, and never kill a process matching `palsync`."
        ])
    ].filter(line => line !== "").join("\n").replace(/\n{3,}/g, "\n\n");
}

function onDemandSyncSections(palName, opts = {}) {
    const full = syncDetails(null, opts);
    const creatingAt = full.indexOf("### Creating new files");
    const datasetsAt = full.indexOf("### Datasets");
    return [
        { id: "sync-workflow", keywords: ["sync", "workflow", "push", "pull", "test", "browser", "runtime", "lock", "drift"], content: full.slice(0, creatingAt).trim() },
        { id: "creating-files", keywords: ["create", "file", "manifest", "pal.json", "page", "fragment", "workflow", "wizard"], content: full.slice(creatingAt, datasetsAt).trim() },
        { id: "datasets", keywords: ["dataset", "schema", "table", "sync", "recreate", "dataview"], content: full.slice(datasetsAt).trim() }
    ];
}

// The single palsync-owned doc: the static PalBuilder coding contract (bundled CLAUDE.md) + the
// templated sync-etiquette/creation/dataset rules, under one version stamp. Written byte-for-byte to
// CLAUDE.palsync.md (and inlined into AGENTS.md for codex/pi) — regenerated wholesale every setup, so
// the rules live in ONE place and cannot drift between two files.
async function buildPalsyncParts(palName, opts = {}) {
    const skillsDir = opts.skillsDir || ".claude/skills";
    let contract = (await fs.readFile(path.join(BUNDLE_DIR, "CLAUDE.md"), "utf8")).trim();
    if (skillsDir !== ".claude/skills") contract = contract.split(".claude/skills").join(skillsDir);
    return { stamp: stampComment(), contract, sync: syncSection(palName, opts) };
}

async function buildPalsyncDoc(palName, opts = {}) {
    const parts = await buildPalsyncParts(palName, opts);
    return [parts.stamp, "", parts.contract, "", "---", "", parts.sync].join("\n") + "\n";
}

// CLAUDE.md managed block (Claude): a REAL `@import` of the owned doc — must be on its own line and
// NOT inside backticks, or Claude Code's import parser skips it (it ignores code spans). Tiny + stable:
// only the stamp changes between versions, so re-inject never churns the user's surrounding prose.
function importBlock() {
    return [BEGIN,
        stampComment(),
        "PalBuilder rules for this pal are maintained by palsync in `CLAUDE.palsync.md` and loaded via",
        "the import below. It is regenerated on each `palsync` launch — edit it only through palsync.",
        "",
        "@CLAUDE.palsync.md",
        END].join("\n");
}

// AGENTS.md managed block (codex/pi): the FULL doc inlined. Those agents read AGENTS.md natively but
// their `@import` support is unreliable, so the rules go in directly rather than via a reference.
function agentsBlock(doc) {
    return BEGIN + "\n" + doc.trimEnd() + "\n" + END;
}

// Insert or replace the managed block, preserving all user content outside the markers.
function mergeManaged(existing, block) {
    if (existing == null) {
        return { content: block + "\n", mode: "created" };
    }
    const b = existing.indexOf(BEGIN);
    const e = existing.indexOf(END);
    if (b !== -1 && e !== -1 && e > b) {
        // Replace existing managed region in place; keep everything else verbatim.
        const before = existing.slice(0, b);
        const after = existing.slice(e + END.length);
        return { content: before + block + after, mode: "refreshed" };
    }
    // Append the block, preserving the user's existing content above it.
    const sep = existing.endsWith("\n") ? "\n" : "\n\n";
    return { content: existing + sep + block + "\n", mode: "appended" };
}

async function copyFile(src, dest) {
    return writeIfChanged(dest, await fs.readFile(src));
}

async function readIfExists(p) {
    try { return await fs.readFile(p, "utf8"); }
    catch (e) { if (e.code === "ENOENT") return null; throw e; }
}

async function filesUnder(dir, prefix) {
    let entries;
    try { entries = await fs.readdir(dir, { withFileTypes: true }); }
    catch (e) { if (e.code === "ENOENT") return []; throw e; }
    const out = [];
    for (const ent of entries.sort((a, b) => a.name < b.name ? -1 : a.name > b.name ? 1 : 0)) {
        const rel = path.join(prefix, ent.name);
        if (ent.isDirectory()) out.push(...await filesUnder(path.join(dir, ent.name), rel));
        else if (ent.isFile()) out.push(rel);
    }
    return out;
}

// Discover every skill shipped in the bundle: each subdir of bundled-context/skills/ that has a
// SKILL.md, normalized to { name, assets } where assets are the files under its references/
// (auto-shipped). The bundle dir is the single source of truth — no list to keep in sync with disk.
async function bundledSkills() {
    const skillsRoot = path.join(BUNDLE_DIR, "skills");
    let entries;
    try { entries = await fs.readdir(skillsRoot, { withFileTypes: true }); }
    catch (e) { if (e.code === "ENOENT") return []; throw e; }
    const out = [];
    for (const ent of entries.sort((a, b) => a.name < b.name ? -1 : a.name > b.name ? 1 : 0)) {
        if (!ent.isDirectory()) continue;
        const dir = path.join(skillsRoot, ent.name);
        try { await fs.access(path.join(dir, "SKILL.md")); }
        catch (e) { continue; } // a dir without SKILL.md is not a skill — skip it
        let assets = [];
        try {
            assets = await filesUnder(path.join(dir, "references"), "references");
        } catch (e) { /* no references/ — SKILL.md-only skill */ }
        out.push({ name: ent.name, assets });
    }
    return out.sort((a, b) => a.name < b.name ? -1 : a.name > b.name ? 1 : 0);
}

// Copy a skill set's SKILL.md (+ companion assets) into <rootDir>/skills/<name>/.
// rootDir is the agent's skills root: ".claude" (Claude) or ".agents" (Codex open standard).
async function copySkillSet(workspaceDir, rootDir, skills) {
    for (const s of skills) {
        await copyFile(path.join(BUNDLE_DIR, "skills", s.name, "SKILL.md"),
                       path.join(workspaceDir, rootDir, "skills", s.name, "SKILL.md"));
        for (const asset of (s.assets || [])) {
            await copyFile(path.join(BUNDLE_DIR, "skills", s.name, asset),
                           path.join(workspaceDir, rootDir, "skills", s.name, asset));
        }
    }
}

// Shared references are companion assets, not a discoverable skill, so they intentionally have
// no SKILL.md. Copy them beside the real skills or every ../shared/... pointer injected into a
// fresh workspace is broken.
async function copySharedReferences(workspaceDir, rootDir) {
    const sourceRoot = path.join(BUNDLE_DIR, "skills", SHARED_REFERENCES, "references");
    for (const asset of await filesUnder(sourceRoot, "references")) {
        await copyFile(path.join(BUNDLE_DIR, "skills", SHARED_REFERENCES, asset),
                       path.join(workspaceDir, rootDir, "skills", SHARED_REFERENCES, asset));
    }
}

// OpenCode discovers SKILL.md files for its agent-facing skill tool, but unlike Claude Code it does
// not also expose those skills as slash commands. A tiny project command bridges the two systems:
// `/pal-loop foo` sends a prompt that loads pal-loop through the skill tool, with `foo` preserved as
// additional user input. Only files carrying our marker are overwritten or pruned; a user-authored
// command with the same name wins and is never clobbered.
function openCodeSkillCommand(name) {
    return [
        "---",
        "description: Load and run the " + name + " skill",
        "---",
        "",
        OPENCODE_COMMAND_MARKER,
        "Use the skill tool to load `" + name + "`, then follow that skill to complete the request.",
        "Treat this as additional user input for the skill: $ARGUMENTS",
        ""
    ].join("\n");
}

async function syncOpenCodeCommands(workspaceDir, skills) {
    const commandsDir = path.join(workspaceDir, ".opencode", "commands");
    const keep = new Set(skills.map(s => s.name));
    const written = [];
    const skipped = [];
    const removed = [];

    for (const skill of skills) {
        const dest = path.join(commandsDir, skill.name + ".md");
        const existing = await readIfExists(dest);
        if (existing != null && !existing.includes(OPENCODE_COMMAND_MARKER)) {
            skipped.push(skill.name);
            continue;
        }
        await writeIfChanged(dest, openCodeSkillCommand(skill.name));
        written.push(skill.name);
    }

    let entries = [];
    try { entries = await fs.readdir(commandsDir, { withFileTypes: true }); }
    catch (e) { if (e.code !== "ENOENT") throw e; }
    for (const ent of entries.sort((a, b) => a.name < b.name ? -1 : a.name > b.name ? 1 : 0)) {
        if (!ent.isFile() || path.extname(ent.name) !== ".md") continue;
        const name = path.basename(ent.name, ".md");
        if (keep.has(name)) continue;
        const filePath = path.join(commandsDir, ent.name);
        const contents = await readIfExists(filePath);
        if (contents != null && contents.includes(OPENCODE_COMMAND_MARKER)) {
            await fs.rm(filePath, { force: true });
            removed.push(name);
        }
    }
    return { written, skipped, removed };
}

async function cleanOpenCodeCommands(workspaceDir) {
    const commandsDir = path.join(workspaceDir, ".opencode", "commands");
    let entries;
    try { entries = await fs.readdir(commandsDir, { withFileTypes: true }); }
    catch (e) { if (e.code === "ENOENT") return []; throw e; }
    const removed = [];
    for (const ent of entries.sort((a, b) => a.name < b.name ? -1 : a.name > b.name ? 1 : 0)) {
        if (!ent.isFile() || path.extname(ent.name) !== ".md") continue;
        const filePath = path.join(commandsDir, ent.name);
        const contents = await readIfExists(filePath);
        if (contents != null && contents.includes(OPENCODE_COMMAND_MARKER)) {
            await fs.rm(filePath, { force: true });
            removed.push(path.basename(ent.name, ".md"));
        }
    }
    await rmDirIfEmpty(commandsDir);
    await rmDirIfEmpty(path.join(workspaceDir, ".opencode"));
    return removed;
}

// Every skill name palsync owns (current + retired). Used by pruneSkills to know which dirs are safe
// to remove — anything outside this set is a user-added skill and is left alone.
async function ownedSkillNames() {
    const names = (await bundledSkills()).map(s => s.name);
    return new Set([...names, SHARED_REFERENCES, ...RETIRED_SKILLS]);
}

// Remove palsync-owned skill dirs that are NOT in the effective set for this session (a skill that was
// dropped from always-on, renamed, or retired). copySkillSet only adds; without this the set only grows
// and stale skills linger forever. Returns the names removed.
async function pruneSkills(workspaceDir, rootDir, keepNames) {
    const skillsDir = path.join(workspaceDir, rootDir, "skills");
    let entries;
    try { entries = await fs.readdir(skillsDir, { withFileTypes: true }); }
    catch (e) { if (e.code === "ENOENT") return []; throw e; }
    const keep = new Set(keepNames);
    if (keep.size) keep.add(SHARED_REFERENCES);
    const owned = await ownedSkillNames();
    const removed = [];
    for (const ent of entries.sort((a, b) => a.name < b.name ? -1 : a.name > b.name ? 1 : 0)) {
        if (!ent.isDirectory()) continue;
        if (owned.has(ent.name) && !keep.has(ent.name)) {
            await fs.rm(path.join(skillsDir, ent.name), { recursive: true, force: true });
            removed.push(ent.name);
        }
    }
    return removed;
}

// Remove a workspace's managed block from a file, preserving any user content outside the markers.
// Deletes the file outright if nothing but whitespace remains. No-op if the file or block is absent.
async function stripManaged(filePath) {
    const existing = await readIfExists(filePath);
    if (existing == null) return false;
    const b = existing.indexOf(BEGIN), e = existing.indexOf(END);
    if (b === -1 || e === -1 || e <= b) return false;
    const rest = existing.slice(0, b) + existing.slice(e + END.length);
    if (rest.trim() === "") { await fs.rm(filePath, { force: true }); return true; }
    await writeIfChanged(filePath, rest);
    return true;
}

// A workspace carries files for ONE agent — the one it was last launched with. When the selected agent
// isn't Claude, remove the Claude-owned artifacts (and vice-versa) so a Pi/Codex pal isn't littered with
// dead CLAUDE.* files and duplicate .claude/skills. Only palsync-owned content is touched; user notes in
// CLAUDE.md/AGENTS.md and user-authored skills survive.
// Remove a dir only if it is now empty (rmdir fails with ENOTEMPTY otherwise) — so an emptied
// .claude/skills (and .claude itself) goes, but a dir still holding user settings is left alone.
async function rmDirIfEmpty(dir) {
    try { await fs.rmdir(dir); return true; } catch (e) { return false; }
}
async function pruneAgentRoot(workspaceDir, rootDir) {
    const removed = await pruneSkills(workspaceDir, rootDir, []);
    await rmDirIfEmpty(path.join(workspaceDir, rootDir, "skills"));
    await rmDirIfEmpty(path.join(workspaceDir, rootDir));
    return removed;
}
async function cleanClaudeArtifacts(workspaceDir) {
    await fs.rm(path.join(workspaceDir, "CLAUDE.palsync.md"), { force: true });
    await stripManaged(path.join(workspaceDir, "CLAUDE.md"));
    return pruneAgentRoot(workspaceDir, ".claude");
}
async function cleanAgentsArtifacts(workspaceDir) {
    await stripManaged(path.join(workspaceDir, "AGENTS.md"));
    return pruneAgentRoot(workspaceDir, ".agents");
}

// Read the version stamp off whichever owned doc this workspace carries (CLAUDE.palsync.md for Claude,
// AGENTS.md for Codex/Pi) and compare to the installed build. `palsync status` uses this to flag a
// workspace that predates the current build (relaunch refreshes it).
async function contextStatus(workspaceDir) {
    for (const file of ["CLAUDE.palsync.md", "AGENTS.md"]) {
        const txt = await readIfExists(path.join(workspaceDir, file));
        if (txt == null) continue;
        const m = txt.match(STAMP_RE);
        const version = m ? m[1] : null;
        return { present: true, file, version, current: VERSION, stale: version !== VERSION };
    }
    return { present: false, file: null, version: null, current: VERSION, stale: true };
}

// Inject context into workspaceDir for the SELECTED agent only, and clean the other agent's
// palsync-owned artifacts so a workspace carries exactly the files its agent reads.
//   claude → .claude/skills + CLAUDE.palsync.md (the owned doc) + a tiny CLAUDE.md block that
//            `@CLAUDE.palsync.md`-imports it. Claude Code reads CLAUDE.md and resolves the import.
//   codex/pi/opencode → .agents/skills + AGENTS.md carrying the full doc inline (their @import
//            support is unreliable; Claude Code does not read .agents/ or AGENTS.md — verified).
//            Pi uses the CLI flavor (palsync subcommands, no session lock); Codex and OpenCode use
//            the MCP flavor (both get a registered MCP server — see workspace.js).
async function inject(workspaceDir, { palName, agent = "claude" } = {}) {
    // Ensure transient artifacts are ignored and already-tracked copies are migrated
    // out of the index. This keeps task commits focused on source while leaving disk
    // content and unrelated staging untouched. Best-effort: warnings do not block setup.
    try {
        const wi = getWorkspaceIgnoreSync();
        if (wi) wi.ensureWorkspaceIgnoreSync(workspaceDir);
    } catch (e) { /* best-effort */ }
    const skills = await bundledSkills();
    const skillNames = skills.map(s => s.name);
    const keep = skillNames.concat(SHARED_REFERENCES);

    if (agent === "codex" || agent === "pi" || agent === "opencode") {
        await copySkillSet(workspaceDir, ".agents", skills);
        await copySharedReferences(workspaceDir, ".agents");
        const prunedAgents = await pruneSkills(workspaceDir, ".agents", keep);
        const openCodeCommands = agent === "opencode"
            ? await syncOpenCodeCommands(workspaceDir, skills)
            : { written: [], skipped: [], removed: await cleanOpenCodeCommands(workspaceDir) };
        const docOpts = { cli: agent === "pi", skillsDir: ".agents/skills" };
        const agentsDoc = await buildPalsyncDoc(palName, docOpts);
        const agentsPath = path.join(workspaceDir, "AGENTS.md");
        const existingAgents = await readIfExists(agentsPath);
        const mergedAgents = mergeManaged(existingAgents, agentsBlock(agentsDoc));
        await writeIfChanged(agentsPath, mergedAgents.content);
        const hookSettings = await claudeHooks.configure(workspaceDir, { install: false });
        const cleanedClaude = await cleanClaudeArtifacts(workspaceDir);
        const result = {
            agent,
            skills: [],
            agentSkills: skillNames.map(name => path.join(".agents/skills", name, "SKILL.md")),
            agentsMd: { path: "AGENTS.md", mode: mergedAgents.mode, userContentPreserved: existingAgents != null },
            prunedSkills: prunedAgents,
            cleanedClaudeSkills: cleanedClaude,
            hookSettings,
            openCodeCommands,
            version: VERSION
        };
        result.contextManifest = await require("../core/contextManifest").emitManifest(workspaceDir, {
            agent, palName, skills, parts: await buildPalsyncParts(palName, docOpts)
        });
        return result;
    }

    // Claude (default).
    await copySkillSet(workspaceDir, ".claude", skills);
    await copySharedReferences(workspaceDir, ".claude");
    const prunedClaude = await pruneSkills(workspaceDir, ".claude", keep);
    const docOpts = { cli: false };
    await writeIfChanged(path.join(workspaceDir, "CLAUDE.palsync.md"),
        await buildPalsyncDoc(palName, docOpts));
    const claudePath = path.join(workspaceDir, "CLAUDE.md");
    const existingClaude = await readIfExists(claudePath);
    const mergedClaude = mergeManaged(existingClaude, importBlock());
    await writeIfChanged(claudePath, mergedClaude.content);
    const cleanedAgents = await cleanAgentsArtifacts(workspaceDir);
    const cleanedOpenCodeCommands = await cleanOpenCodeCommands(workspaceDir);
    const hookSettings = await claudeHooks.configure(workspaceDir, { install: true });
    const result = {
        agent,
        skills: skillNames.map(name => path.join(".claude/skills", name, "SKILL.md")),
        agentSkills: [],
        claudePalsync: "CLAUDE.palsync.md",
        claudeMd: { path: "CLAUDE.md", mode: mergedClaude.mode, userContentPreserved: existingClaude != null },
        prunedSkills: prunedClaude,
        cleanedAgentsSkills: cleanedAgents,
        cleanedOpenCodeCommands,
        hookSettings,
        version: VERSION
    };
    result.contextManifest = await require("../core/contextManifest").emitManifest(workspaceDir, {
        agent, palName, skills, parts: await buildPalsyncParts(palName, docOpts)
    });
    return result;
}

module.exports = { inject, mergeManaged, importBlock, agentsBlock, buildPalsyncDoc, buildPalsyncParts, syncSection, syncDetails, onDemandSyncSections,
    pruneSkills, stripManaged, cleanClaudeArtifacts, cleanAgentsArtifacts, contextStatus,
    syncOpenCodeCommands, cleanOpenCodeCommands, openCodeSkillCommand,
    BEGIN, END, OPENCODE_COMMAND_MARKER, BUNDLE_DIR, VERSION, bundledSkills, ownedSkillNames };
